//creating warehouses, databases and schema
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS ECOMMERCE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB;

CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.ANALYTICS;


//Confirm check
SHOW WAREHOUSES LIKE 'ECOMMERCE_WH';
SHOW DATABASES LIKE 'ECOMMERCE_DB';
SHOW SCHEMAS IN DATABASE ECOMMERCE_DB;

USE WAREHOUSE ECOMMERCE_WH;
USE DATABASE ECOMMERCE_DB;
USE SCHEMA RAW;

SELECT
    CURRENT_ROLE(),
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();


//cost safety net
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS ECOMMERCE_COST_MONITOR
    WITH CREDIT_QUOTA = 1
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 50 PERCENT DO NOTIFY
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE ECOMMERCE_WH
    SET RESOURCE_MONITOR = ECOMMERCE_COST_MONITOR;

SHOW RESOURCE MONITORS LIKE 'ECOMMERCE_COST_MONITOR';

USE ROLE ACCOUNTADMIN;

ALTER RESOURCE MONITOR ECOMMERCE_COST_MONITOR
SET CREDIT_QUOTA = 5;

ALTER WAREHOUSE ECOMMERCE_WH RESUME;
show warehouses;

ALTER WAREHOUSE ECOMMERCE_WH SUSPEND;
show warehouses; 