USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS ECOMMERCE_DEVELOPER
    COMMENT = 'Developer role for Olist E-Commerce Analytics project';

USE ROLE SECURITYADMIN;

GRANT USAGE
    ON WAREHOUSE ECOMMERCE_WH
    TO ROLE ECOMMERCE_DEVELOPER;

GRANT USAGE
    ON DATABASE ECOMMERCE_DB
    TO ROLE ECOMMERCE_DEVELOPER;

GRANT USAGE
    ON SCHEMA ECOMMERCE_DB.RAW
    TO ROLE ECOMMERCE_DEVELOPER;

GRANT USAGE
    ON SCHEMA ECOMMERCE_DB.STAGING
    TO ROLE ECOMMERCE_DEVELOPER;

GRANT USAGE
    ON SCHEMA ECOMMERCE_DB.ANALYTICS
    TO ROLE ECOMMERCE_DEVELOPER;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA ECOMMERCE_DB.RAW
    TO ROLE ECOMMERCE_DEVELOPER;

GRANT CREATE TABLE, CREATE VIEW
    ON SCHEMA ECOMMERCE_DB.STAGING
    TO ROLE ECOMMERCE_DEVELOPER;

GRANT CREATE TABLE, CREATE VIEW
    ON SCHEMA ECOMMERCE_DB.ANALYTICS
    TO ROLE ECOMMERCE_DEVELOPER;

GRANT ROLE ECOMMERCE_DEVELOPER TO ROLE SYSADMIN;

SELECT CURRENT_USER();

USE ROLE SECURITYADMIN;

GRANT ROLE ECOMMERCE_DEVELOPER TO USER SATYAMSONI;

//test
USE ROLE ECOMMERCE_DEVELOPER;

USE WAREHOUSE ECOMMERCE_WH;
USE DATABASE ECOMMERCE_DB;
USE SCHEMA RAW;

SELECT
    CURRENT_USER(),
    CURRENT_ROLE(),
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();
