USE ROLE ECOMMERCE_DEVELOPER;
USE WAREHOUSE ECOMMERCE_WH;
USE DATABASE ECOMMERCE_DB;
USE SCHEMA RAW;

//csv file format
CREATE OR REPLACE FILE FORMAT ECOMMERCE_DB.RAW.OLIST_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null')
    TRIM_SPACE = TRUE;

//internal stage
CREATE OR REPLACE STAGE ECOMMERCE_DB.RAW.OLIST_STAGE
    FILE_FORMAT = ECOMMERCE_DB.RAW.OLIST_CSV_FORMAT;

//verify
SHOW FILE FORMATS IN SCHEMA ECOMMERCE_DB.RAW;
SHOW STAGES IN SCHEMA ECOMMERCE_DB.RAW;

LIST @ECOMMERCE_DB.RAW.OLIST_STAGE;

//after uploading
LIST @ECOMMERCE_DB.RAW.OLIST_STAGE;

ALTER WAREHOUSE ECOMMERCE_WH SUSPEND;
SHOW WAREHOUSES LIKE 'ECOMMERCE_WH';